// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmchWrVSk1kQ6p0zNEOKHaqzvTKoQ3xxc',
    appId: '1:426142602614:web:2e8940a7fd558867299657',
    messagingSenderId: '426142602614',
    projectId: 'fluttertask-1-1318c',
    authDomain: 'fluttertask-1-1318c.firebaseapp.com',
    storageBucket: 'fluttertask-1-1318c.firebasestorage.app',
    measurementId: 'G-TEKFJ33JL6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAI-t4tC6K4FJ6hsMC6viUzvZUEf9ahHP4',
    appId: '1:426142602614:android:bf13c61098e20057299657',
    messagingSenderId: '426142602614',
    projectId: 'fluttertask-1-1318c',
    storageBucket: 'fluttertask-1-1318c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPuNFinYB-gW-PNrnYDShr8wrsjCTb0fE',
    appId: '1:426142602614:ios:8d1a3f4693f7dfe2299657',
    messagingSenderId: '426142602614',
    projectId: 'fluttertask-1-1318c',
    storageBucket: 'fluttertask-1-1318c.firebasestorage.app',
    iosBundleId: 'com.example.flutterTask1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPuNFinYB-gW-PNrnYDShr8wrsjCTb0fE',
    appId: '1:426142602614:ios:8d1a3f4693f7dfe2299657',
    messagingSenderId: '426142602614',
    projectId: 'fluttertask-1-1318c',
    storageBucket: 'fluttertask-1-1318c.firebasestorage.app',
    iosBundleId: 'com.example.flutterTask1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmchWrVSk1kQ6p0zNEOKHaqzvTKoQ3xxc',
    appId: '1:426142602614:web:afdfc090cd2c0bce299657',
    messagingSenderId: '426142602614',
    projectId: 'fluttertask-1-1318c',
    authDomain: 'fluttertask-1-1318c.firebaseapp.com',
    storageBucket: 'fluttertask-1-1318c.firebasestorage.app',
    measurementId: 'G-HE098YC8JS',
  );
}
